# Numpy

>  The NumPy library is the core library for scientific computing in
Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays

#  Installing numpy

In [3]:
!pip install numpy

     |████████████████████████████████| 15.7 MB 2.1 MB/s eta 0:00:01    |█▋                              | 808 kB 2.1 MB/s eta 0:00:08     |█████████████████████████████▌  | 14.5 MB 2.1 MB/s eta 0:00:01


In [30]:
import numpy as np

# Creating Arrays

In [60]:
arr1=np.array([2,3,4])
arr1.shape

(3,)

In [59]:
arr2=np.array([(1,2,3),(4,5,6),(7,8,9)])
arr2.shape

(3, 3)

In [61]:
arr3=np.array([[(1,2,3),(4,5,6),(7,8,9)],[(1,2,3),(4,5,6),(7,8,9)]])
arr3.shape

(2, 3, 3)

# Initial Placeholders

In [64]:
a=np.zeros((2,3,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [68]:
b=np.ones((2,3,5),dtype=np.int16)
b

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [72]:
c=np.arange(10,25,5)
c

array([10, 15, 20])

In [78]:
d=np.linspace(1,100,10)
d

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [81]:
e=np.full((2,3),7)
e

array([[7, 7, 7],
       [7, 7, 7]])

In [83]:
f=np.eye(2) # 2x2 identy metrix
f

array([[1., 0.],
       [0., 1.]])

In [88]:
g=np.random.random(10) # Create a array with random values
g

array([0.00901297, 0.10026887, 0.81167544, 0.51281356, 0.77858003,
       0.72412537, 0.8390938 , 0.76295676, 0.73737176, 0.01830857])

In [91]:
h=np.empty((3,2))
h

array([[1.31197907e-316, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

# I/O

## Saving & Loading On Disk

In [92]:
np.save("my_array",b)

In [93]:
np.savez("my_arrayz",b,c)

In [ ]:
b=np.load("my_array.npy")
b

## Saving & Loading Text Files

In [108]:
np.loadtxt("myfile.txt")

array([0.00901297, 0.10026887, 0.81167544, 0.51281356, 0.77858003,
       0.72412537, 0.8390938 , 0.76295676, 0.73737176, 0.01830857])

In [110]:
# np.getfromtxt("myfile.csv",delimiter=",")


In [111]:
np.savetxt("myfile.txt",g,delimiter=" ")

# Data Types

In [122]:
# np.int64
# np.float32
# np.complex
# np.bool
# np.object
# np.string_

# Inspecting Your Array

In [129]:
arr3=np.array([[(1,2,3),(4,5,6),(7,8,9)],[(1,2,3),(4,5,6),(7,8,9)]])
arr3


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [130]:
arr3.shape

(2, 3, 3)

In [127]:
arr3.ndim

3

In [131]:
len(arr3)

2

In [132]:
arr3.size #Number of array elements

18

In [133]:
arr3.dtype

dtype('int64')

In [134]:
arr3.dtype.name

'int64'

In [137]:
 arr3.astype(float)  # Convert datatype

array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]])

# Asking For Help

In [138]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


# Array Mathematics

## 1. Arithmetic Operations

In [148]:
x=np.array((1,2,3),dtype=float)
x

array([1., 2., 3.])

In [149]:
y=np.array([(1.5,2.5,3.5),(4,5,6)],dtype=float)
y

array([[1.5, 2.5, 3.5],
       [4. , 5. , 6. ]])

In [152]:
z=x-y
z

array([[-0.5, -0.5, -0.5],
       [-3. , -3. , -3. ]])

In [153]:
np.subtract(x,y)

array([[-0.5, -0.5, -0.5],
       [-3. , -3. , -3. ]])

In [154]:
x+y

array([[2.5, 4.5, 6.5],
       [5. , 7. , 9. ]])

In [155]:
np.add(x,y)

array([[2.5, 4.5, 6.5],
       [5. , 7. , 9. ]])

In [156]:
x/y

array([[0.66666667, 0.8       , 0.85714286],
       [0.25      , 0.4       , 0.5       ]])

In [159]:
np.divide(x,y)

array([[0.66666667, 0.8       , 0.85714286],
       [0.25      , 0.4       , 0.5       ]])

In [160]:
x*y

array([[ 1.5,  5. , 10.5],
       [ 4. , 10. , 18. ]])

In [161]:
np.multiply(x,y)

array([[ 1.5,  5. , 10.5],
       [ 4. , 10. , 18. ]])

In [162]:
np.exp(y)

array([[  4.48168907,  12.18249396,  33.11545196],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [165]:
np.sqrt(y)

array([[1.22474487, 1.58113883, 1.87082869],
       [2.        , 2.23606798, 2.44948974]])

In [166]:
np.sin(y)

array([[ 0.99749499,  0.59847214, -0.35078323],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [167]:
np.cos(x)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [168]:
np.log(y)

array([[0.40546511, 0.91629073, 1.25276297],
       [1.38629436, 1.60943791, 1.79175947]])

# Comparison

In [171]:
x==y # Element-wise comparison

array([[False, False, False],
       [False, False, False]])

In [172]:
x>y # Element-wise comparison

array([[False, False, False],
       [False, False, False]])

In [173]:
np.array_equal(x, y) 

False

# Aggregate Functions

In [174]:
x.sum()

6.0

In [175]:
x.mean()

2.0

In [176]:
x.max()

3.0

In [178]:
y.cumsum(axis=1)

array([[ 1.5,  4. ,  7.5],
       [ 4. ,  9. , 15. ]])

# Copying Arrays

In [185]:
h=x.view() #Create a view of the array with the same data
h

array([1., 2., 3.])

In [187]:
np.copy(x) #Create a copy of the array

array([1., 2., 3.])

In [189]:
h=x.copy() # Create a  deep copy of the array
h

array([1., 2., 3.])

# Sorting Arrays

In [194]:
y.sort()
y

array([[1.5, 2.5, 3.5],
       [4. , 5. , 6. ]])

In [193]:
x.sort(axis=1)
x

AxisError: axis 1 is out of bounds for array of dimension 1

# Subsetting, Slicing, Indexing

# Array Manipulation

##  Transposing Array

##  Changing Array Shape