# Numpy

>  The NumPy library is the core library for scientific computing in
Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays

#  Installing numpy

In [3]:
!pip install numpy

     |████████████████████████████████| 15.7 MB 2.1 MB/s eta 0:00:01    |█▋                              | 808 kB 2.1 MB/s eta 0:00:08     |█████████████████████████████▌  | 14.5 MB 2.1 MB/s eta 0:00:01


In [30]:
import numpy as np

# Creating Arrays

In [60]:
arr1=np.array([2,3,4])
arr1.shape

(3,)

In [59]:
arr2=np.array([(1,2,3),(4,5,6),(7,8,9)])
arr2.shape

(3, 3)

In [61]:
arr3=np.array([[(1,2,3),(4,5,6),(7,8,9)],[(1,2,3),(4,5,6),(7,8,9)]])
arr3.shape

(2, 3, 3)

# Initial Placeholders

In [64]:
a=np.zeros((2,3,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [68]:
b=np.ones((2,3,5),dtype=np.int16)
b

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [72]:
c=np.arange(10,25,5)
c

array([10, 15, 20])

In [78]:
d=np.linspace(1,100,10)
d

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [81]:
e=np.full((2,3),7)
e

array([[7, 7, 7],
       [7, 7, 7]])

In [83]:
f=np.eye(2) # 2x2 identy metrix
f

array([[1., 0.],
       [0., 1.]])

In [88]:
g=np.random.random(10) # Create a array with random values
g

array([0.00901297, 0.10026887, 0.81167544, 0.51281356, 0.77858003,
       0.72412537, 0.8390938 , 0.76295676, 0.73737176, 0.01830857])

In [91]:
h=np.empty((3,2))
h

array([[1.31197907e-316, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

# I/O

## Saving & Loading On Disk

In [92]:
np.save("my_array",b)

In [93]:
np.savez("my_arrayz",b,c)

In [ ]:
b=np.load("my_array.npy")
b

## Saving & Loading Text Files

In [108]:
np.loadtxt("myfile.txt")

array([0.00901297, 0.10026887, 0.81167544, 0.51281356, 0.77858003,
       0.72412537, 0.8390938 , 0.76295676, 0.73737176, 0.01830857])

In [110]:
# np.getfromtxt("myfile.csv",delimiter=",")


In [111]:
np.savetxt("myfile.txt",g,delimiter=" ")

# Data Types

In [122]:
# np.int64
# np.float32
# np.complex
# np.bool
# np.object
# np.string_

# Inspecting Your Array

# Asking For Help

# Array Mathematics

## Arithmetic Operations

# Comparison

# Aggregate Functions

# Copying Arrays

# Sorting Arrays

# Subsetting, Slicing, Indexing

# Array Manipulation

##  Transposing Array

##  Changing Array Shape